### ISSUE TITLE
[Bug]: F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [lihenggui/blocker#156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

```
...
Calculating task graph as no configuration cache is available for tasks: clean
> Task :build-logic:convention:pluginDescriptors
> Task :build-logic:convention:processResources

> Task :build-logic:convention:compileKotlin
e: /home/vagrant/build/com.merxury.blocker/build-logic/convention/src/main/kotlin/AndroidApplicationFirebaseConventionPlugin.kt: (18, 19): Unresolved reference: firebase
e: /home/vagrant/build/com.merxury.blocker/build-logic/convention/src/main/kotlin/AndroidApplicationFirebaseConventionPlugin.kt: (44, 53): Unresolved reference: CrashlyticsExtension
e: /home/vagrant/build/com.merxury.blocker/build-logic/convention/src/main/kotlin/AndroidApplicationFirebaseConventionPlugin.kt: (45, 37): Variable expected

> Task :build-logic:convention:compileKotlin FAILED
```

Since we clean the proprietary libraries from the source with
```
    prebuild:
      - sed -i -e '/"firebase"/,+3d' -e '/firebase/d' ../build-logic/convention/build.gradle.kts
      - sed -i -e '/gms/d' -e '/firebase/d' build.gradle.kts ../build.gradle.kts
```

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/4536d7333936f98b952b98172e607445e54778ef

**Comment by licaon-kter** [comment]
I might have missed the "new" `flavor` section, where is that exactly? How is that gradle flavor named?

**Comment by lihenggui** [comment]
Or if you want to remove the dependency from the code completely, you can remove code in these two files: 

https://github.com/lihenggui/blocker/blob/main/app-compose/build.gradle.kts#L27
Remove `id("blocker.android.application.firebase")`

Then in https://github.com/lihenggui/blocker/blob/main/build.gradle.kts#L29
Remove these three lines
```
    alias(libs.plugins.firebase.crashlytics) apply false
    alias(libs.plugins.firebase.perf) apply false
    alias(libs.plugins.gms) apply false
```

**Comment by licaon-kter** [comment]
The thing is, the old flavor was named `basic` (https://gitlab.com/fdroid/fdroiddata/-/blob/4536d7333936f98b952b98172e607445e54778ef/metadata/com.merxury.blocker.yml#L36) and when I tested earlier I couldn't locate where you define this `foss` flavor.

Will retry with `foss` asap.

**Comment by lihenggui** [comment]
Blocker did refactor and rewrite almost all the code recently. The previous flavor name is not clear, so I renamed it to foss, which means this version is for FOSS markets. 

Could you tell me what's the right approach to maintain the F-droid version, then I can do it for you.

**Comment by licaon-kter** [comment]
Trying with `foss` now, found it here: https://github.com/lihenggui/blocker/blob/2.0.1701/build-logic/convention/src/main/kotlin/com/merxury/blocker/BlockerFlavor.kt#L33 :)

**Comment by licaon-kter** [comment]
> Could you tell me what's the right approach to maintain the F-droid version, then I can do it for you.

In what way? Just having a fully FOSS flavor should be enought

Running now for `foss` flavor... fails: 
[com.merxury.blocker_1270.log.gz](https://github.com/lihenggui/blocker/files/11039517/com.merxury.blocker_1270.log.gz)

> Or if you want to remove the dependency from the code completely, you can remove code in these two files:

Trying that next

**Comment by lihenggui** [comment]
> > Could you tell me what's the right approach to maintain the F-droid version, then I can do it for you.
> 
> In what way? Just having a fully FOSS flavor should be enough
> 
> Running now for `foss` flavor... fails: [com.merxury.blocker_1270.log.gz](https://github.com/lihenggui/blocker/files/11039517/com.merxury.blocker_1270.log.gz)
> 
> > Or if you want to remove the dependency from the code completely, you can remove code in these two files:
> 
> Trying that next
> 
> /LE: steps go like this:
> 
> * sync sources
> * run `gradle clean`
> * clean-up all the bad stuff (see those classes being "removed" in the log)
> * then run `gradle assembleFossRelease`
> * fail

The error on your file is 
```
* Where:
Build file '/home/vagrant/build/com.merxury.blocker/app/build.gradle.kts' line: 21

* What went wrong:
Plugin [id: 'blocker.android.application'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Included Builds (None of the included builds contain this plugin)
- Plugin Repositories (plugin dependency must include a version number for this source)
```
Looks like it relates to some configuration (But it shouldn't happen)

On my Mac the command `assembleFossRelease` works normally. Are you using a Windows PC?

**Comment by lihenggui** [comment]
I use `./gradlew :app-compose:clean :app-compose:assembleFossRelease :app-compose:bundleFossRelease` and it works.

**Comment by licaon-kter** [comment]
Debian Linux Bullseye amd64 clean VM

I think the issue is that we run
> `gradle clean`
> clean-up all the bad stuff _(see those classes being "removed" in the log)_

Is by any chance `Plugin [id: 'blocker.android.application']` generated during `gradle clean`  too?

**Comment by licaon-kter** [comment]
The exact recipe is this:
```
  - versionName: 1.2.70
    versionCode: 1270
    commit: 96e22f6b1b7ca451c0f531b796c160741ba5023f
    subdir: app
    gradle:
      - foss
    scandelete:
      - build-logic
    prebuild:
      - sed -i -e '/"firebase"/,+3d' -e '/firebase/d' ../build-logic/convention/build.gradle.kts
      - sed -i -e '/gms/d' -e '/firebase/d' build.gradle.kts ../build.gradle.kts ../app-compose/build.gradle.kts
```

So can you test by running those two `sed` in the `app` folder and THEN try to build?

**Comment by lihenggui** [comment]
Can you kindly explain how I can run this recipe on my computer?

**Comment by licaon-kter** [comment]
You don't need to run fdroidserver, just run those two `sed` commands in your `app` folder then try to build  `gradle assembleFossRelease`

**Comment by lihenggui** [comment]
It will show an error.
`sed: -e: No such file or directory`

I am using MacOS Ventura 13.2.1 (22D68)

**Comment by licaon-kter** [comment]
ok, try

`sed -i '' -e '/"firebase"/,+3d' -e '/firebase/d' ../build-logic/convention/build.gradle.kts`
`sed -i '' -e '/gms/d' -e '/firebase/d' build.gradle.kts ../build.gradle.kts ../app-compose/build.gradle.kts`

**Comment by lihenggui** [comment]
If you decided to remove code, you also need to delete AndroidApplicationFirebaseConventionPlugin.kt in `build-convention` project.
https://github.com/lihenggui/blocker/blob/main/build-logic/convention/src/main/kotlin/AndroidApplicationFirebaseConventionPlugin.kt
Then assembleFossRelease works

**Comment by licaon-kter** [comment]
Will try asap, thanks

**Comment by licaon-kter** [comment]
Ah, slipped by.... retrying...

**Comment by licaon-kter** [comment]
This is pulled in `foss`: https://github.com/lihenggui/blocker/blob/badbf798b52fe99f69abe901ca1e793cfe10e18c/core/analytics/build.gradle.kts#L32-L33

This recipe:
```
  - versionName: 1.2.70
    versionCode: 1270
    commit: 96e22f6b1b7ca451c0f531b796c160741ba5023f
    subdir: app
    gradle:
      - foss
    scandelete:
      - build-logic
    prebuild:
      - sed -i -e '/"firebase"/,+3d' -e '/firebase/d' ../build-logic/convention/build.gradle.kts
      - sed -i -e '/gms/d' -e '/firebase/d' build.gradle.kts ../build.gradle.kts ../app-compose/build.gradle.kts
    rm:
      - build-logic/convention/src/main/kotlin/AndroidApplicationFirebaseConventionPlugin.kt
```

**Comment by lihenggui** [comment]
Hi @licaon-kter 
The FOSS variant used an empty implementation for analytic tasks. I can either try using `marketImplementation` or just remove the dependencies.

**Comment by licaon-kter** [comment]
Empty or not it pulls in real non-FOSS libs :) so yeah... nuke them

**Comment by lihenggui** [comment]
I am modifying it, please wait

**Comment by licaon-kter** [comment]
This recipe:
```
  - versionName: 1.2.70
    versionCode: 1270
    commit: d92bd4f9dafba854c7ee9714f6ee6ba61f8ebea0
    subdir: app
    gradle:
      - foss
    scandelete:
      - build-logic
```
...fails at `gradle clean`:
```
2023-04-12 13:01:54,241 INFO: Cleaning Gradle project...
2023-04-12 13:01:54,242 DEBUG: Directory: build/com.merxury.blocker/app
2023-04-12 13:01:54,242 DEBUG: > /home/vagrant/fdroidserver/gradlew-fdroid clean

Here are the highlights of this release:
 - Added support for Java 19.
 - Introduced `--rerun` flag for individual task rerun.
 - Improved dependency block for test suites to be strongly typed.
 - Added a pluggable system for Java toolchains provisioning.

For more details see https://docs.gradle.org/7.6/release-notes.html

To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.6/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build 
Configuration cache is an incubating feature.
Calculating task graph as no configuration cache is available for tasks: clean

FAILURE: Build failed with an exception.

* What went wrong:
Project directory '/home/vagrant/build/com.merxury.blocker/app' is not part of the build defined by settings file '/home/vagrant/build/com.merxury.blocker/settings.gradle.kts'. If this is an unrelated build, it must have its own settings file.
```

**Comment by lihenggui** [comment]
> 

Ah I see.
You are building the application in the 'app' folder, which is an archive of the old version of the Blocker.
You can just run the command in the root folder of the project, it should work.

The new app project locates in the `app-compose` folder, and if you are trying to run `./gradlew clean assembleFossRelease`, the output should locate in `[project root]/app-compose/build/outputs/apk/foss/release/app-compose-foss-release.apk`

**Comment by lihenggui** [comment]
@licaon-kter Could you please try again?

**Comment by lihenggui** [comment]
Hi @licaon-kter Can you try again?

**Comment by licaon-kter** [comment]
Recipe:
```
  - versionName: 2.0.1705
    versionCode: 1705
    commit: 96e22f6b1b7ca451c0f531b796c160741ba5023f
    subdir: app-compose
    gradle:
      - foss
    prebuild: sed -i -e '/gms/d' -e '/firebase/d' build.gradle.kts ../build.gradle.kts
```
...fails:
```
...
DEBUG: Directory: build/com.merxury.blocker/app-compose
DEBUG: > /home/vagrant/fdroidserver/gradlew-fdroid clean
Found 7.6 via distributionUrl
Downloading missing gradle version 7.6
cachedir /home/vagrant/.cache/fdroidserver
/home/vagrant/.cache/fdroidserver/gradle-7.6-bin.zip: OK
Running /opt/gradle/versions/7.6/bin/gradle clean

To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.6/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build 
Configuration cache is an incubating feature.
Calculating task graph as no configuration cache is available for tasks: clean
> Task :build-logic:convention:pluginDescriptors
> Task :build-logic:convention:processResources
> Task :build-logic:convention:compileKotlin
> Task :build-logic:convention:compileJava NO-SOURCE
> Task :build-logic:convention:classes
> Task :build-logic:convention:inspectClassesForKotlinIC
> Task :build-logic:convention:jar

0 problems were found storing the configuration cache.

See the complete report at file:///home/vagrant/build/com.merxury.blocker/build/reports/configuration-cache/18adsa9cil4ygmbksw64xzz6g/72w2ukgd0j71c58ov19fhmu5o/configuration-cache-report.html

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Plugin with id 'com.google.gms.google-services' not found.
```

**Comment by lihenggui** [comment]
There is no need to run the pre-build script now.
Just assemble Foss variant, it will not contain closed source libraries.

./gradlew clean assembleFossRelease

**Comment by lihenggui** [comment]
I see the build number is old. Could you pull your code to the latest one?

**Comment by licaon-kter** [comment]
> There is no need to run the pre-build script now.

We run `gradle clean` first

> Just assemble Foss variant, it will not contain closed source libraries.

Will do in the next steps... it we reach them :)

> I see the build number is old.

That's pulled from your APK: https://github.com/lihenggui/blocker/releases/tag/2.0.1701 -> https://github.com/lihenggui/blocker/releases/download/2.0.1701/Blocker-2.0.1705-release.apk.apk 

> Could you pull your code to the latest one?

Not sure what https://github.com/lihenggui/blocker/blob/main/app-compose/build.gradle.kts#L38-L39 should yield

Or you mean it's elsewhere https://github.com/lihenggui/blocker/blob/2.0.1701/app/build.gradle.kts#L37-L38 ?

You said `app-compose` and there's no static one to read from there....

**Comment by licaon-kter** [comment]
@lihenggui I can use any commit but makes sense to use the ones you deemed taggable :)

**Comment by lihenggui** [comment]
Hi @licaon-kter Can you try building the tag [v2.0.2006](https://github.com/lihenggui/blocker/releases/tag/v2.0.2006) with command `./gradlew clean assembleFossRelease`?

**Comment by lihenggui** [comment]
Hi @licaon-kter Can you build the app right now?

**Comment by lihenggui** [comment]
hi @licaon-kter last check. Is it working now?

**Comment by licaon-kter** [comment]
> Can you try building the tag [v2.0.2006](https://github.com/lihenggui/blocker/releases/tag/v2.0.2006)

It fails before it gets to that step, at `gradle clean`
```
> Configure project :build-logic:convention
e: /home/vagrant/build/com.merxury.blocker/build-logic/convention/build.gradle.kts:32:22: Unresolved reference: firebase
e: /home/vagrant/build/com.merxury.blocker/build-logic/convention/build.gradle.kts:33:22: Unresolved reference: firebase

0 problems were found storing the configuration cache.

See the complete report at file:///home/vagrant/build/com.merxury.blocker/build/reports/configuration-cache/18adsa9cil4ygmbksw64xzz6g/9xyp6gsw30platimxjqifs1ii/configuration-cache-report.html

FAILURE: Build failed with an exception.

* Where:
Build file '/home/vagrant/build/com.merxury.blocker/build-logic/convention/build.gradle.kts' line: 32

* What went wrong:
Script compilation errors:

  Line 32:     compileOnly(libs.firebase.performance.gradle)

  Line 33:     compileOnly(libs.firebase.crashlytics.gradle)
                                ^ Unresolved reference: firebase

2 errors
```

**Comment by lihenggui** [comment]
Can you try to build the latest main branch or tag v2.0.2031-pre-release?
I checked the file `build-logic/convention/build.gradle.kts`, there are no such lines in this file and gradle clean works.

And I also want to check with you, I switched to the v2.0.2006 version and there are no such lines in `build-logic/convention/build.gradle.kts` either. Could you please check if the checkout is done successfully or not?

**Comment by licaon-kter** [comment]
Ah looks like I've mixed the recipe files and it tried to build old one still :facepalm: my bad

Retrying now

**Comment by licaon-kter** [comment]
This recipe
```
  - versionName: 2.0.2006
    versionCode: 1270
    commit: 96e22f6b1b7ca451c0f531b796c160741ba5023f
    subdir: app-compose
    gradle:
      - foss
    prebuild: sed -i -e '/register("firebase/,+3d' -e '/gms/d' -e '/firebase/d' build.gradle.kts
        ../build.gradle.kts ../app/build.gradle.kts ../build-logic/convention/build.gradle.kts
        ../gradle/libs.versions.toml
```

Fails
```
> Task :build-logic:convention:pluginDescriptors
> Task :build-logic:convention:processResources

> Task :build-logic:convention:compileKotlin
e: /home/vagrant/build/com.merxury.blocker/build-logic/convention/src/main/kotlin/AndroidApplicationFirebaseConventionPlugin.kt: (18, 19): Unresolved reference: firebase
e: /home/vagrant/build/com.merxury.blocker/build-logic/convention/src/main/kotlin/AndroidApplicationFirebaseConventionPlugin.kt: (44, 53): Unresolved reference: CrashlyticsExtension
e: /home/vagrant/build/com.merxury.blocker/build-logic/convention/src/main/kotlin/AndroidApplicationFirebaseConventionPlugin.kt: (45, 37): Variable expected

> Task :build-logic:convention:compileKotlin FAILED
```

Did I miss more firebase/gms cleanup steps?

**Comment by lihenggui** [comment]
You don't need to run receipt to remove gms related things before building.
You can just run `gradle assembleFossRelease` to get the foss build.

**Comment by lihenggui** [comment]
I disabled all firebase related task in foss build in build script

**Comment by lihenggui** [comment]
https://github.com/lihenggui/blocker/blob/main/build-logic/convention/src/main/kotlin/AndroidApplicationFirebaseConventionPlugin.kt#L50
Check this

**Comment by licaon-kter** [comment]
> You don't need to run recipe to remove gms related things before building.

Check this: https://github.com/lihenggui/blocker/blob/main/build-logic/convention/src/main/kotlin/AndroidApplicationFirebaseConventionPlugin.kt#L19

That will fail since the `com.google.firebase.*` will not be present at **compile** time... since I need to remove them.

**Comment by lihenggui** [comment]
Do you have to remove all firebase occurrences before building the app?
Even if the lib is removed in the build script?

**Comment by licaon-kter** [comment]
Yes, we can't have any non-FOSS deps being used for compile either

If there's nothing there, there's no need to "remove in the build script" :)

**Comment by lihenggui** [comment]
I disabled all firebase related tasks so in the final apk output there is
no crashlytics/analytics/gms included.
I thought running the recipe is just a workaround.

**Comment by licaon-kter** [comment]
We need to remove:
* https://github.com/lihenggui/blocker/blob/main/build-logic/convention/build.gradle.kts#L39-L40
* https://github.com/lihenggui/blocker/blob/main/build-logic/convention/build.gradle.kts#L86-L89
* https://github.com/lihenggui/blocker/blob/main/build.gradle.kts#L22-L26
* https://github.com/lihenggui/blocker/blob/main/build.gradle.kts#L34-L36
* https://github.com/lihenggui/blocker/blob/main/app-compose/build.gradle.kts#L25
* https://github.com/lihenggui/blocker/blob/main/app-compose/build.gradle.kts#L28
* https://github.com/lihenggui/blocker/blob/main/gradle/libs.versions.toml#L35-L41
* https://github.com/lihenggui/blocker/blob/main/gradle/libs.versions.toml#L119-L128
* https://github.com/lihenggui/blocker/blob/main/gradle/libs.versions.toml#L170-L172
...at least

**Comment by lihenggui** [comment]
Shall I make a build script for F-droid build to delete these lines automatically?

**Comment by licaon-kter** [comment]
The recipe above https://github.com/lihenggui/blocker/issues/156#issuecomment-1662435421 does this, not the issue.

The problem is that the code still depends on the non-FOSS libs to compile

**Comment by lihenggui** [comment]
https://github.com/lihenggui/blocker/commit/71bafcb9f393750eff43eb5a408f80c0ed55a42d

We should remove these lines.
I checked that clean / assembleFossRelease task works

**Comment by licaon-kter** [comment]
A step forward I guess, this recipe:
```
  - versionName: 1.2.70
    versionCode: 1270
    commit: 71bafcb9f393750eff43eb5a408f80c0ed55a42d
    subdir: app-compose
    sudo:
      - apt-get update
      - apt-get install -y openjdk-17-jdk-headless
      - update-alternatives --auto java
    gradle:
      - foss
    prebuild: sed -i -e '/androidx.dev/d' ../settings.gradle.kts
    scandelete:
      - build-logic
```
fails
```
FAILURE: Build failed with an exception.

* What went wrong:
Configuration cache state could not be cached: field `__pluginClasspath__` of task `:core:analytics:compileFossReleaseKotlin` of type `org.jetbrains.kotlin.gradle.tasks.KotlinCompile`: error writing value of type 'org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection'
> Could not resolve all files for configuration ':core:analytics:kotlin-extension'.
   > Could not find androidx.compose.compiler:compiler:1.5.0-dev-k1.9.0-6a60475e07f.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/androidx/compose/compiler/compiler/1.5.0-dev-k1.9.0-6a60475e07f/compiler-1.5.0-dev-k1.9.0-6a60475e07f.pom
       - https://repo.maven.apache.org/maven2/androidx/compose/compiler/compiler/1.5.0-dev-k1.9.0-6a60475e07f/compiler-1.5.0-dev-k1.9.0-6a60475e07f.pom
       - https://jitpack.io/androidx/compose/compiler/compiler/1.5.0-dev-k1.9.0-6a60475e07f/compiler-1.5.0-dev-k1.9.0-6a60475e07f.pom
     Required by:
         project :core:analytics
```
... notice that I removed the untrusted androidX maven repo

**Comment by lihenggui** [comment]
> A step forward I guess, this recipe:
> 
> ```
>   - versionName: 1.2.70
>     versionCode: 1270
>     commit: 71bafcb9f393750eff43eb5a408f80c0ed55a42d
>     subdir: app-compose
>     sudo:
>       - apt-get update
>       - apt-get install -y openjdk-17-jdk-headless
>       - update-alternatives --auto java
>     gradle:
>       - foss
>     prebuild: sed -i -e '/androidx.dev/d' ../settings.gradle.kts
>     scandelete:
>       - build-logic
> ```
> 
> fails
> 
> ```
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Configuration cache state could not be cached: field `__pluginClasspath__` of task `:core:analytics:compileFossReleaseKotlin` of type `org.jetbrains.kotlin.gradle.tasks.KotlinCompile`: error writing value of type 'org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection'
> > Could not resolve all files for configuration ':core:analytics:kotlin-extension'.
>    > Could not find androidx.compose.compiler:compiler:1.5.0-dev-k1.9.0-6a60475e07f.
>      Searched in the following locations:
>        - https://dl.google.com/dl/android/maven2/androidx/compose/compiler/compiler/1.5.0-dev-k1.9.0-6a60475e07f/compiler-1.5.0-dev-k1.9.0-6a60475e07f.pom
>        - https://repo.maven.apache.org/maven2/androidx/compose/compiler/compiler/1.5.0-dev-k1.9.0-6a60475e07f/compiler-1.5.0-dev-k1.9.0-6a60475e07f.pom
>        - https://jitpack.io/androidx/compose/compiler/compiler/1.5.0-dev-k1.9.0-6a60475e07f/compiler-1.5.0-dev-k1.9.0-6a60475e07f.pom
>      Required by:
>          project :core:analytics
> ```
> 
> ... notice that I removed the untrusted androidX maven repo

The version code is wrong, you are using the old codebase. 
Can you try checkout the latest tags and remove the lines mentioned above? Or you can checkout the fdroid branch.

**Comment by licaon-kter** [comment]
I can't guess the versionCode and Name from this https://github.com/lihenggui/blocker/blob/71bafcb9f393750eff43eb5a408f80c0ed55a42d/app-compose/build.gradle.kts#L37-L38

also they don't matter, I did checkout the right thing, you can see right below `commit: 71bafcb9f393750eff43eb5a408f80c0ed55a42d`

**Comment by lihenggui** [comment]
I get it, I used the pre-release version of the Compose compiler.
https://androidx.dev/storage/compose-compiler/repository

Is that OK to use this repository? If not, I need to downgrade the Compose compiler to the release version.

**Comment by lihenggui** [comment]
I checked that androidx.dev shipped the library with the source code:
https://androidx.dev/storage/compose-compiler/repository/androidx/compose/compiler/compiler-hosted/1.5.0-dev-k1.9.0-6a60475e07f/compiler-hosted-1.5.0-dev-k1.9.0-6a60475e07f-sources.jar

**Comment by licaon-kter** [comment]
We can't use that repo now.

Whether we could trust it in the future, it's another discussion.

**Comment by lihenggui** [comment]
> We can't use that repo now.
> 
> Whether we could trust it in the future, it's another discussion.

This repo was removed in https://github.com/lihenggui/blocker/pull/248/files

**Comment by licaon-kter** [comment]
You didn't update the `fdroid` brach so I had to apply the commit manually
```
  - versionName: 2.0.2113
    versionCode: 2113
    commit: 71bafcb9f393750eff43eb5a408f80c0ed55a42d
    subdir: app-compose
    sudo:
      - apt-get update
      - apt-get install -y openjdk-17-jdk-headless
      - update-alternatives --auto java
    gradle:
      - foss
    prebuild:
      - sed -i -e 's/1.5.0-dev-k1.9.0-6a60475e07f/1.5.1/' ../gradle/libs.versions.toml
      - sed -i -e '/androidx.dev/d' ../settings.gradle.kts
    scandelete:
      - build-logic
```

and this builds fine

Now, regarding the way forward:
* you are going to have a separate branch and Tag separately like `2.0.2113-fdroid` ?
* is there a reason for dynamic version* ? https://github.com/lihenggui/blocker/blob/main/app-compose/build.gradle.kts#L39-L40 F-Droid won't calculate these, so autoupdates will be disabled leaving you/me/others to have to come and open a merge request when/if we notice a new version
